spring:
  application:
    name: uniclub
  datasource:
    url: jdbc:mysql://localhost:3307/uniclub
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

jwt:
  key: JWtbxQTwEO2oSPgo0uBtnBrucw0wmEZNO//1Bhd+qxw=

upload:
  path: D:\images

